### ISSUE TITLE
Account for different DL link patterns

### ISSUE THREAD

**Issue by ddeanto** [ddeanto/py-life#1]
recent link circa 2017: https://od.lk/download/M18xNjExOTI5NjJf?
link circa 2015: https://app.box.com/s/lq9xiykf9r61kfxch5mu9by3k79zeks8

OR WE COULD just say fuck it and only allow scraping > 2015

@dsynk do you say fuck it? or is <= 2015 important?

**Comment by dsynk** [comment]
Sorry just saw this. I would say that this thing is being designed as a
daily job, so fuck it. If I want the older shit I'll modify the script
accordingly and run it once.

Not sure if this is still an issue, btw.

**Comment by ddeanto** [comment]
closing the issue cuz @dsynk says it aint relevant
